# Generated by Django 5.0.6 on 2024-06-11 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
