# Generated by Django 5.0.6 on 2024-06-12 22:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0003_rename_usuarios_usuario_rename_id_user_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_cliente',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField()),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='grillmaster.genero')),
            ],
        ),
    ]
