# Generated by Django 5.0.6 on 2024-06-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0004_genero_registro_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
