# Generated by Django 5.0.6 on 2024-06-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0006_productos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_cliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registro_cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registro_cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='registro_cliente',
            name='password',
        ),
        migrations.AddField(
            model_name='registro_cliente',
            name='username',
            field=models.CharField(default=2, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
