# Generated by Django 5.0.6 on 2024-06-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0009_registro_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_cliente',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='registro_cliente',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Registro_cliente',
        ),
    ]
