# Generated by Django 5.0.6 on 2024-06-19 04:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0011_genero_registro_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='id_producto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='cantidad',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='grillmaster.categoria', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('taxes', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('shipping', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grillmaster.productos')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grillmaster.orden')),
            ],
        ),
    ]
