# Generated by Django 5.0.6 on 2024-06-19 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0012_categoria_rename_descripcion_productos_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grillmaster.categoria', verbose_name='Categoria'),
        ),
    ]
