# Generated by Django 5.0.6 on 2024-06-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0013_alter_productos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesContacto',
            fields=[
                ('opciones', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Opcion de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('reason', models.ForeignKey(db_column='Opciones', on_delete=django.db.models.deletion.CASCADE, to='grillmaster.opcionescontacto')),
            ],
        ),
    ]
