# Generated by Django 5.0.6 on 2024-06-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grillmaster', '0014_opcionescontacto_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_orden',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='grillmaster.orden'),
        ),
    ]
